name: firebase_auth_mocks
description: Fakes for Firebase Auth. Use this package with `google_sign_in_mocks` to write unit tests involving Firebase Authentication.
version: 0.8.5+1
homepage: https://www.wafrat.com
repository: https://github.com/atn832/firebase_auth_mocks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.5.0
  meta: ^1.3.0
  equatable: ^2.0.0
  dart_jsonwebtoken: ^2.4.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.0.0
  jwt_decoder: ^2.0.1
