name: firebase_auth_mocks
description: Fakes for Firebase Auth. Use this package with `google_sign_in_mocks` to write unit tests involving Firebase Authentication.
version: 0.15.0
homepage: https://www.wafrat.com
repository: https://github.com/atn832/firebase_auth_mocks

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  meta: ^1.16.0
  equatable: ^2.0.0
  dart_jsonwebtoken: ^3.2.0
  uuid: ^4.1.0
  firebase_auth_platform_interface: ^8.0.0
  mock_exceptions: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.0.0
  jwt_decoder: ^2.0.1
